# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vcom -work work +acc /home/ojakinlade/Documents/cocotb/adder/tests/../hdl/adder.vhd
vsim  -onfinish exit -t 1ps -foreign "cocotb_init /home/ojakinlade/Documents/cocotb/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbfli_modelsim.so"   sim_build/work.adder
onbreak resume
run -all
quit
