# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vcom -work work +acc ~/Documents/Quartus/cocotb_add_sum/IP/lpm_add_sub_ip.vhd ~/Documents/Quartus/cocotb_add_sum/src/add_sub_top.vhd
vsim  -onfinish exit -t 1ps -foreign "cocotb_init /home/ojakinlade/Documents/cocotb/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbfli_modelsim.so"   sim_build/work.add_sub_top
onbreak resume
run -all
quit
